# Site settings
title: My Blog
SEOTitle: 我的博客 | My Blog
theme: jekyll-theme-cayman
url: "http://yangchch6.github.io"          # name改成你的ID
baseurl: "/blog"      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yangchch6/YangChenchen.github.io.git" # 用你的ID替换name

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "苟利国家生死以，岂因祸福避趋之~"
sidebar-avatar: /img/avatar_binggan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username: 暂无
zhihu_username:     暂无
github_username:    暂无
facebook_username:  暂无
jianshu_username:   暂无
#twitter_username: 暂无
